services:

  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: dispatchanddelivery
      POSTGRES_PASSWORD: secret
    volumes:
      - dispatchanddelivery-pg-local:/var/lib/postgresql/data
    ports:
      - "5400:5432"

volumes:
  dispatchanddelivery-pg-local:
